# fly.toml app configuration file generated for superdev-assignment-hidden-voice-5095 on 2025-06-30T23:43:08+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'superdev-assignment-hidden-voice-5095'
primary_region = 'bom'

[build]

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
